/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SchemeIdeSetup /* implements SchemeStandaloneSetup  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nSchemeRuntimeModule cannot be resolved."
      + "\nType mismatch: cannot convert from SchemeIdeModule to Module");
  }
}
