/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br;

import fm.pucrs.br.SCHStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SCHStandaloneSetup extends SCHStandaloneSetupGenerated {
  public static void doSetup() {
    new SCHStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
