/*
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.ui;

import com.google.inject.Injector;
import fm.pucrs.br.ui.internal.BrActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SCHExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BrActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BrActivator.getInstance().getInjector(BrActivator.FM_PUCRS_BR_SCH);
	}
	
}
