/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH.impl;

import fm.pucrs.br.sCH.MoreOrEqual;
import fm.pucrs.br.sCH.SCHPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>More Or Equal</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.impl.MoreOrEqualImpl#getMoreOrEqual <em>More Or Equal</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MoreOrEqualImpl extends LogicOperatorImpl implements MoreOrEqual
{
  /**
   * The default value of the '{@link #getMoreOrEqual() <em>More Or Equal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMoreOrEqual()
   * @generated
   * @ordered
   */
  protected static final String MORE_OR_EQUAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMoreOrEqual() <em>More Or Equal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMoreOrEqual()
   * @generated
   * @ordered
   */
  protected String moreOrEqual = MORE_OR_EQUAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MoreOrEqualImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SCHPackage.Literals.MORE_OR_EQUAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMoreOrEqual()
  {
    return moreOrEqual;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMoreOrEqual(String newMoreOrEqual)
  {
    String oldMoreOrEqual = moreOrEqual;
    moreOrEqual = newMoreOrEqual;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SCHPackage.MORE_OR_EQUAL__MORE_OR_EQUAL, oldMoreOrEqual, moreOrEqual));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SCHPackage.MORE_OR_EQUAL__MORE_OR_EQUAL:
        return getMoreOrEqual();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SCHPackage.MORE_OR_EQUAL__MORE_OR_EQUAL:
        setMoreOrEqual((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SCHPackage.MORE_OR_EQUAL__MORE_OR_EQUAL:
        setMoreOrEqual(MORE_OR_EQUAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SCHPackage.MORE_OR_EQUAL__MORE_OR_EQUAL:
        return MORE_OR_EQUAL_EDEFAULT == null ? moreOrEqual != null : !MORE_OR_EQUAL_EDEFAULT.equals(moreOrEqual);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (moreOrEqual: ");
    result.append(moreOrEqual);
    result.append(')');
    return result.toString();
  }

} //MoreOrEqualImpl
