/*
 * generated by Xtext 2.13.0
 */
package fm.pucrs.br.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SCHGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.Program");
		private final Assignment cExpressionsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cExpressionsExpressionParserRuleCall_0 = (RuleCall)cExpressionsAssignment.eContents().get(0);
		
		//Program:
		//	expressions+=Expression+;
		@Override public ParserRule getRule() { return rule; }
		
		//expressions+=Expression+
		public Assignment getExpressionsAssignment() { return cExpressionsAssignment; }
		
		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_0() { return cExpressionsExpressionParserRuleCall_0; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAtomParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cListParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Expression:
		//	Atom | List;
		@Override public ParserRule getRule() { return rule; }
		
		//Atom | List
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Atom
		public RuleCall getAtomParserRuleCall_0() { return cAtomParserRuleCall_0; }
		
		//List
		public RuleCall getListParserRuleCall_1() { return cListParserRuleCall_1; }
	}
	public class AtomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.Atom");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIDexpParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cINTexpParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBOOLexpParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDOUBLEexpParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cSTRexpParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Atom:
		//	IDexp | INTexp | BOOLexp | DOUBLEexp | STRexp;
		@Override public ParserRule getRule() { return rule; }
		
		//IDexp | INTexp | BOOLexp | DOUBLEexp | STRexp
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IDexp
		public RuleCall getIDexpParserRuleCall_0() { return cIDexpParserRuleCall_0; }
		
		//INTexp
		public RuleCall getINTexpParserRuleCall_1() { return cINTexpParserRuleCall_1; }
		
		//BOOLexp
		public RuleCall getBOOLexpParserRuleCall_2() { return cBOOLexpParserRuleCall_2; }
		
		//DOUBLEexp
		public RuleCall getDOUBLEexpParserRuleCall_3() { return cDOUBLEexpParserRuleCall_3; }
		
		//STRexp
		public RuleCall getSTRexpParserRuleCall_4() { return cSTRexpParserRuleCall_4; }
	}
	public class IDexpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.IDexp");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//IDexp:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class INTexpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.INTexp");
		private final Assignment cIvalueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIvalueINTTerminalRuleCall_0 = (RuleCall)cIvalueAssignment.eContents().get(0);
		
		//INTexp:
		//	ivalue=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//ivalue=INT
		public Assignment getIvalueAssignment() { return cIvalueAssignment; }
		
		//INT
		public RuleCall getIvalueINTTerminalRuleCall_0() { return cIvalueINTTerminalRuleCall_0; }
	}
	public class DOUBLEexpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.DOUBLEexp");
		private final Assignment cDvalueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cDvalueDOUBLETerminalRuleCall_0 = (RuleCall)cDvalueAssignment.eContents().get(0);
		
		//DOUBLEexp:
		//	dvalue=DOUBLE;
		@Override public ParserRule getRule() { return rule; }
		
		//dvalue=DOUBLE
		public Assignment getDvalueAssignment() { return cDvalueAssignment; }
		
		//DOUBLE
		public RuleCall getDvalueDOUBLETerminalRuleCall_0() { return cDvalueDOUBLETerminalRuleCall_0; }
	}
	public class BOOLexpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.BOOLexp");
		private final Assignment cBvalueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cBvalueBOOLEANTerminalRuleCall_0 = (RuleCall)cBvalueAssignment.eContents().get(0);
		
		//BOOLexp:
		//	bvalue=BOOLEAN;
		@Override public ParserRule getRule() { return rule; }
		
		//bvalue=BOOLEAN
		public Assignment getBvalueAssignment() { return cBvalueAssignment; }
		
		//BOOLEAN
		public RuleCall getBvalueBOOLEANTerminalRuleCall_0() { return cBvalueBOOLEANTerminalRuleCall_0; }
	}
	public class STRexpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.STRexp");
		private final Assignment cSvalueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cSvalueSTRINGTerminalRuleCall_0 = (RuleCall)cSvalueAssignment.eContents().get(0);
		
		//STRexp:
		//	svalue=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//svalue=STRING
		public Assignment getSvalueAssignment() { return cSvalueAssignment; }
		
		//STRING
		public RuleCall getSvalueSTRINGTerminalRuleCall_0() { return cSvalueSTRINGTerminalRuleCall_0; }
	}
	public class ListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.List");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCalledAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCalledIDTerminalRuleCall_1_0 = (RuleCall)cCalledAssignment_1.eContents().get(0);
		private final Assignment cParamsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParamsExpressionParserRuleCall_2_0 = (RuleCall)cParamsAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//List:
		//	'(' called=ID params+=Expression* ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' called=ID params+=Expression* ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//called=ID
		public Assignment getCalledAssignment_1() { return cCalledAssignment_1; }
		
		//ID
		public RuleCall getCalledIDTerminalRuleCall_1_0() { return cCalledIDTerminalRuleCall_1_0; }
		
		//params+=Expression*
		public Assignment getParamsAssignment_2() { return cParamsAssignment_2; }
		
		//Expression
		public RuleCall getParamsExpressionParserRuleCall_2_0() { return cParamsExpressionParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	
	
	private final ProgramElements pProgram;
	private final ExpressionElements pExpression;
	private final AtomElements pAtom;
	private final IDexpElements pIDexp;
	private final INTexpElements pINTexp;
	private final DOUBLEexpElements pDOUBLEexp;
	private final BOOLexpElements pBOOLexp;
	private final STRexpElements pSTRexp;
	private final ListElements pList;
	private final TerminalRule tDOUBLE;
	private final TerminalRule tBOOLEAN;
	private final TerminalRule tID;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SCHGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pExpression = new ExpressionElements();
		this.pAtom = new AtomElements();
		this.pIDexp = new IDexpElements();
		this.pINTexp = new INTexpElements();
		this.pDOUBLEexp = new DOUBLEexpElements();
		this.pBOOLexp = new BOOLexpElements();
		this.pSTRexp = new STRexpElements();
		this.pList = new ListElements();
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.DOUBLE");
		this.tBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.BOOLEAN");
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "fm.pucrs.br.SCH.ID");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fm.pucrs.br.SCH".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//	expressions+=Expression+;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Expression:
	//	Atom | List;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Atom:
	//	IDexp | INTexp | BOOLexp | DOUBLEexp | STRexp;
	public AtomElements getAtomAccess() {
		return pAtom;
	}
	
	public ParserRule getAtomRule() {
		return getAtomAccess().getRule();
	}
	
	//IDexp:
	//	name=ID;
	public IDexpElements getIDexpAccess() {
		return pIDexp;
	}
	
	public ParserRule getIDexpRule() {
		return getIDexpAccess().getRule();
	}
	
	//INTexp:
	//	ivalue=INT;
	public INTexpElements getINTexpAccess() {
		return pINTexp;
	}
	
	public ParserRule getINTexpRule() {
		return getINTexpAccess().getRule();
	}
	
	//DOUBLEexp:
	//	dvalue=DOUBLE;
	public DOUBLEexpElements getDOUBLEexpAccess() {
		return pDOUBLEexp;
	}
	
	public ParserRule getDOUBLEexpRule() {
		return getDOUBLEexpAccess().getRule();
	}
	
	//BOOLexp:
	//	bvalue=BOOLEAN;
	public BOOLexpElements getBOOLexpAccess() {
		return pBOOLexp;
	}
	
	public ParserRule getBOOLexpRule() {
		return getBOOLexpAccess().getRule();
	}
	
	//STRexp:
	//	svalue=STRING;
	public STRexpElements getSTRexpAccess() {
		return pSTRexp;
	}
	
	public ParserRule getSTRexpRule() {
		return getSTRexpAccess().getRule();
	}
	
	//List:
	//	'(' called=ID params+=Expression* ')';
	public ListElements getListAccess() {
		return pList;
	}
	
	public ParserRule getListRule() {
		return getListAccess().getRule();
	}
	
	//terminal DOUBLE:
	//	INT '.' INT;
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	}
	
	//terminal BOOLEAN:
	//	'#t' | '#f';
	public TerminalRule getBOOLEANRule() {
		return tBOOLEAN;
	}
	
	//@ Override terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9' | '!')* | '+' | '-' | '*' | '/' | '=' | '<' |
	//	'>' | '<=' | '>=';
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
