/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.tests;

import com.google.inject.Inject;
import fm.pucrs.br.tests.SCHInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(SCHInjectorProvider.class)
@SuppressWarnings("all")
public class SCHParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel1() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SCHParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
  
  @Test
  public void loadModel2() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SCHParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
  
  @Test
  public void loadModel3() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SCHParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
  
  @Test
  public void loadModel4() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SCHParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
  
  @Test
  public void loadModel5() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SCHParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
  
  @Test
  public void loadModel6() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SCHParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
  
  @Test
  public void loadModel7() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SCHParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
  
  @Test
  public void loadModel8() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SCHParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
  
  @Test
  public void loadModel9() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SCHParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
