/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.scoping;

import fm.pucrs.br.scoping.AbstractSCHScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SCHScopeProvider extends AbstractSCHScopeProvider {
}
