/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.ui;

import fm.pucrs.br.ui.AbstractSCHUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SCHUiModule extends AbstractSCHUiModule {
  public SCHUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
