/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.Add#getPlus <em>Plus</em>}</li>
 * </ul>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getAdd()
 * @model
 * @generated
 */
public interface Add extends Operator
{
  /**
   * Returns the value of the '<em><b>Plus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Plus</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plus</em>' attribute.
   * @see #setPlus(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getAdd_Plus()
   * @model
   * @generated
   */
  String getPlus();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Add#getPlus <em>Plus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plus</em>' attribute.
   * @see #getPlus()
   * @generated
   */
  void setPlus(String value);

} // Add
