/**
 * generated by Xtext 2.13.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atom</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.Atom#getName <em>Name</em>}</li>
 *   <li>{@link fm.pucrs.br.sCH.Atom#getIvalue <em>Ivalue</em>}</li>
 *   <li>{@link fm.pucrs.br.sCH.Atom#getBvalue <em>Bvalue</em>}</li>
 *   <li>{@link fm.pucrs.br.sCH.Atom#getDvalue <em>Dvalue</em>}</li>
 *   <li>{@link fm.pucrs.br.sCH.Atom#getSvalue <em>Svalue</em>}</li>
 * </ul>
 * </p>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getAtom()
 * @model
 * @generated
 */
public interface Atom extends Expression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getAtom_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Atom#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ivalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ivalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ivalue</em>' attribute.
   * @see #setIvalue(int)
   * @see fm.pucrs.br.sCH.SCHPackage#getAtom_Ivalue()
   * @model
   * @generated
   */
  int getIvalue();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Atom#getIvalue <em>Ivalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ivalue</em>' attribute.
   * @see #getIvalue()
   * @generated
   */
  void setIvalue(int value);

  /**
   * Returns the value of the '<em><b>Bvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bvalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bvalue</em>' attribute.
   * @see #setBvalue(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getAtom_Bvalue()
   * @model
   * @generated
   */
  String getBvalue();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Atom#getBvalue <em>Bvalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bvalue</em>' attribute.
   * @see #getBvalue()
   * @generated
   */
  void setBvalue(String value);

  /**
   * Returns the value of the '<em><b>Dvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dvalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dvalue</em>' attribute.
   * @see #setDvalue(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getAtom_Dvalue()
   * @model
   * @generated
   */
  String getDvalue();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Atom#getDvalue <em>Dvalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dvalue</em>' attribute.
   * @see #getDvalue()
   * @generated
   */
  void setDvalue(String value);

  /**
   * Returns the value of the '<em><b>Svalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Svalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Svalue</em>' attribute.
   * @see #setSvalue(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getAtom_Svalue()
   * @model
   * @generated
   */
  String getSvalue();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Atom#getSvalue <em>Svalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Svalue</em>' attribute.
   * @see #getSvalue()
   * @generated
   */
  void setSvalue(String value);

} // Atom
