/**
 * generated by Xtext 2.13.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BOO Lexp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.BOOLexp#getBvalue <em>Bvalue</em>}</li>
 * </ul>
 * </p>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getBOOLexp()
 * @model
 * @generated
 */
public interface BOOLexp extends Atom
{
  /**
   * Returns the value of the '<em><b>Bvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bvalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bvalue</em>' attribute.
   * @see #setBvalue(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getBOOLexp_Bvalue()
   * @model
   * @generated
   */
  String getBvalue();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.BOOLexp#getBvalue <em>Bvalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bvalue</em>' attribute.
   * @see #getBvalue()
   * @generated
   */
  void setBvalue(String value);

} // BOOLexp
