/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Define</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.Define#getId <em>Id</em>}</li>
 *   <li>{@link fm.pucrs.br.sCH.Define#getEx <em>Ex</em>}</li>
 * </ul>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getDefine()
 * @model
 * @generated
 */
public interface Define extends Expression
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getDefine_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Define#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Ex</b></em>' containment reference list.
   * The list contents are of type {@link fm.pucrs.br.sCH.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ex</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ex</em>' containment reference list.
   * @see fm.pucrs.br.sCH.SCHPackage#getDefine_Ex()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getEx();

} // Define
