/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Different</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.Different#getDifferent <em>Different</em>}</li>
 * </ul>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getDifferent()
 * @model
 * @generated
 */
public interface Different extends LogicOperator, Operator
{
  /**
   * Returns the value of the '<em><b>Different</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Different</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Different</em>' attribute.
   * @see #setDifferent(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getDifferent_Different()
   * @model
   * @generated
   */
  String getDifferent();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Different#getDifferent <em>Different</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Different</em>' attribute.
   * @see #getDifferent()
   * @generated
   */
  void setDifferent(String value);

} // Different
