/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Divide</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.Divide#getDiveded <em>Diveded</em>}</li>
 * </ul>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getDivide()
 * @model
 * @generated
 */
public interface Divide extends Operator
{
  /**
   * Returns the value of the '<em><b>Diveded</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Diveded</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Diveded</em>' attribute.
   * @see #setDiveded(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getDivide_Diveded()
   * @model
   * @generated
   */
  String getDiveded();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Divide#getDiveded <em>Diveded</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Diveded</em>' attribute.
   * @see #getDiveded()
   * @generated
   */
  void setDiveded(String value);

} // Divide
