/**
 * generated by Xtext 2.13.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DOUBL Eexp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.DOUBLEexp#getDvalue <em>Dvalue</em>}</li>
 * </ul>
 * </p>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getDOUBLEexp()
 * @model
 * @generated
 */
public interface DOUBLEexp extends Atom
{
  /**
   * Returns the value of the '<em><b>Dvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dvalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dvalue</em>' attribute.
   * @see #setDvalue(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getDOUBLEexp_Dvalue()
   * @model
   * @generated
   */
  String getDvalue();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.DOUBLEexp#getDvalue <em>Dvalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dvalue</em>' attribute.
   * @see #getDvalue()
   * @generated
   */
  void setDvalue(String value);

} // DOUBLEexp
