/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.Equal#getEqual <em>Equal</em>}</li>
 * </ul>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getEqual()
 * @model
 * @generated
 */
public interface Equal extends LogicOperator, Operator
{
  /**
   * Returns the value of the '<em><b>Equal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Equal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Equal</em>' attribute.
   * @see #setEqual(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getEqual_Equal()
   * @model
   * @generated
   */
  String getEqual();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Equal#getEqual <em>Equal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Equal</em>' attribute.
   * @see #getEqual()
   * @generated
   */
  void setEqual(String value);

} // Equal
