/**
 * generated by Xtext 2.13.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IN Texp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.INTexp#getIvalue <em>Ivalue</em>}</li>
 * </ul>
 * </p>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getINTexp()
 * @model
 * @generated
 */
public interface INTexp extends Atom
{
  /**
   * Returns the value of the '<em><b>Ivalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ivalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ivalue</em>' attribute.
   * @see #setIvalue(int)
   * @see fm.pucrs.br.sCH.SCHPackage#getINTexp_Ivalue()
   * @model
   * @generated
   */
  int getIvalue();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.INTexp#getIvalue <em>Ivalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ivalue</em>' attribute.
   * @see #getIvalue()
   * @generated
   */
  void setIvalue(int value);

} // INTexp
