/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Less</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.Less#getLess <em>Less</em>}</li>
 * </ul>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getLess()
 * @model
 * @generated
 */
public interface Less extends LogicOperator, Operator
{
  /**
   * Returns the value of the '<em><b>Less</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Less</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Less</em>' attribute.
   * @see #setLess(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getLess_Less()
   * @model
   * @generated
   */
  String getLess();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Less#getLess <em>Less</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Less</em>' attribute.
   * @see #getLess()
   * @generated
   */
  void setLess(String value);

} // Less
