/**
 * generated by Xtext 2.13.0
 */
package fm.pucrs.br.sCH;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.List#getCalled <em>Called</em>}</li>
 *   <li>{@link fm.pucrs.br.sCH.List#getParams <em>Params</em>}</li>
 * </ul>
 * </p>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getList()
 * @model
 * @generated
 */
public interface List extends Expression
{
  /**
   * Returns the value of the '<em><b>Called</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Called</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Called</em>' attribute.
   * @see #setCalled(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getList_Called()
   * @model
   * @generated
   */
  String getCalled();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.List#getCalled <em>Called</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Called</em>' attribute.
   * @see #getCalled()
   * @generated
   */
  void setCalled(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link fm.pucrs.br.sCH.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see fm.pucrs.br.sCH.SCHPackage#getList_Params()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getParams();

} // List
