/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logic Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getLogicOperator()
 * @model
 * @generated
 */
public interface LogicOperator extends EObject
{
} // LogicOperator
