/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.Model#getExpressions <em>Expressions</em>}</li>
 * </ul>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link fm.pucrs.br.sCH.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see fm.pucrs.br.sCH.SCHPackage#getModel_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getExpressions();

} // Model
