/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>More Or Equal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.MoreOrEqual#getMoreOrEqual <em>More Or Equal</em>}</li>
 * </ul>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getMoreOrEqual()
 * @model
 * @generated
 */
public interface MoreOrEqual extends LogicOperator, Operator
{
  /**
   * Returns the value of the '<em><b>More Or Equal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>More Or Equal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>More Or Equal</em>' attribute.
   * @see #setMoreOrEqual(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getMoreOrEqual_MoreOrEqual()
   * @model
   * @generated
   */
  String getMoreOrEqual();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.MoreOrEqual#getMoreOrEqual <em>More Or Equal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>More Or Equal</em>' attribute.
   * @see #getMoreOrEqual()
   * @generated
   */
  void setMoreOrEqual(String value);

} // MoreOrEqual
