/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiply</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.Multiply#getTimes <em>Times</em>}</li>
 * </ul>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getMultiply()
 * @model
 * @generated
 */
public interface Multiply extends Operator
{
  /**
   * Returns the value of the '<em><b>Times</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Times</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Times</em>' attribute.
   * @see #setTimes(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getMultiply_Times()
   * @model
   * @generated
   */
  String getTimes();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.Multiply#getTimes <em>Times</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Times</em>' attribute.
   * @see #getTimes()
   * @generated
   */
  void setTimes(String value);

} // Multiply
