/**
 * generated by Xtext 2.13.0
 */
package fm.pucrs.br.sCH;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fm.pucrs.br.sCH.SCHFactory
 * @model kind="package"
 * @generated
 */
public interface SCHPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sCH";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.pucrs.fm/br/SCH";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sCH";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SCHPackage eINSTANCE = fm.pucrs.br.sCH.impl.SCHPackageImpl.init();

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.ProgramImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__EXPRESSIONS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.ExpressionImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.AtomImpl <em>Atom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.AtomImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getAtom()
   * @generated
   */
  int ATOM = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ivalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__IVALUE = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Bvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__BVALUE = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Dvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__DVALUE = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Svalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__SVALUE = EXPRESSION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Atom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.ListImpl <em>List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.ListImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getList()
   * @generated
   */
  int LIST = 3;

  /**
   * The feature id for the '<em><b>Called</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__CALLED = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__PARAMS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see fm.pucrs.br.sCH.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link fm.pucrs.br.sCH.Program#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see fm.pucrs.br.sCH.Program#getExpressions()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Expressions();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see fm.pucrs.br.sCH.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Atom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atom</em>'.
   * @see fm.pucrs.br.sCH.Atom
   * @generated
   */
  EClass getAtom();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Atom#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fm.pucrs.br.sCH.Atom#getName()
   * @see #getAtom()
   * @generated
   */
  EAttribute getAtom_Name();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Atom#getIvalue <em>Ivalue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ivalue</em>'.
   * @see fm.pucrs.br.sCH.Atom#getIvalue()
   * @see #getAtom()
   * @generated
   */
  EAttribute getAtom_Ivalue();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Atom#getBvalue <em>Bvalue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bvalue</em>'.
   * @see fm.pucrs.br.sCH.Atom#getBvalue()
   * @see #getAtom()
   * @generated
   */
  EAttribute getAtom_Bvalue();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Atom#getDvalue <em>Dvalue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dvalue</em>'.
   * @see fm.pucrs.br.sCH.Atom#getDvalue()
   * @see #getAtom()
   * @generated
   */
  EAttribute getAtom_Dvalue();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Atom#getSvalue <em>Svalue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Svalue</em>'.
   * @see fm.pucrs.br.sCH.Atom#getSvalue()
   * @see #getAtom()
   * @generated
   */
  EAttribute getAtom_Svalue();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.List <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List</em>'.
   * @see fm.pucrs.br.sCH.List
   * @generated
   */
  EClass getList();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.List#getCalled <em>Called</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Called</em>'.
   * @see fm.pucrs.br.sCH.List#getCalled()
   * @see #getList()
   * @generated
   */
  EAttribute getList_Called();

  /**
   * Returns the meta object for the containment reference list '{@link fm.pucrs.br.sCH.List#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see fm.pucrs.br.sCH.List#getParams()
   * @see #getList()
   * @generated
   */
  EReference getList_Params();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SCHFactory getSCHFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.ProgramImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__EXPRESSIONS = eINSTANCE.getProgram_Expressions();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.ExpressionImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.AtomImpl <em>Atom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.AtomImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getAtom()
     * @generated
     */
    EClass ATOM = eINSTANCE.getAtom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOM__NAME = eINSTANCE.getAtom_Name();

    /**
     * The meta object literal for the '<em><b>Ivalue</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOM__IVALUE = eINSTANCE.getAtom_Ivalue();

    /**
     * The meta object literal for the '<em><b>Bvalue</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOM__BVALUE = eINSTANCE.getAtom_Bvalue();

    /**
     * The meta object literal for the '<em><b>Dvalue</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOM__DVALUE = eINSTANCE.getAtom_Dvalue();

    /**
     * The meta object literal for the '<em><b>Svalue</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOM__SVALUE = eINSTANCE.getAtom_Svalue();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.ListImpl <em>List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.ListImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getList()
     * @generated
     */
    EClass LIST = eINSTANCE.getList();

    /**
     * The meta object literal for the '<em><b>Called</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIST__CALLED = eINSTANCE.getList_Called();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST__PARAMS = eINSTANCE.getList_Params();

  }

} //SCHPackage
