/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.sCH;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fm.pucrs.br.sCH.SCHFactory
 * @model kind="package"
 * @generated
 */
public interface SCHPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sCH";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.pucrs.fm/br/SCH";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sCH";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SCHPackage eINSTANCE = fm.pucrs.br.sCH.impl.SCHPackageImpl.init();

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.ModelImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__EXPRESSIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.ExpressionImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__VALUE = 0;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__IDENTIFIER = 1;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__BOOL = 2;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__STR = 3;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OP = 4;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__LEFT = 5;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__RIGHT = 6;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.DefineImpl <em>Define</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.DefineImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getDefine()
   * @generated
   */
  int DEFINE = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__VALUE = EXPRESSION__VALUE;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__IDENTIFIER = EXPRESSION__IDENTIFIER;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__BOOL = EXPRESSION__BOOL;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__STR = EXPRESSION__STR;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__OP = EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__LEFT = EXPRESSION__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__RIGHT = EXPRESSION__RIGHT;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__ID = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ex</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__EX = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Define</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.LambdaImpl <em>Lambda</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.LambdaImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getLambda()
   * @generated
   */
  int LAMBDA = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__VALUE = EXPRESSION__VALUE;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__IDENTIFIER = EXPRESSION__IDENTIFIER;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__BOOL = EXPRESSION__BOOL;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__STR = EXPRESSION__STR;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__OP = EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__LEFT = EXPRESSION__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__RIGHT = EXPRESSION__RIGHT;

  /**
   * The feature id for the '<em><b>Ouput</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__OUPUT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ex</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__EX = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Lambda</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.IfImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getIf()
   * @generated
   */
  int IF = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__VALUE = EXPRESSION__VALUE;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__IDENTIFIER = EXPRESSION__IDENTIFIER;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__BOOL = EXPRESSION__BOOL;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__STR = EXPRESSION__STR;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__OP = EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__LEFT = EXPRESSION__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__RIGHT = EXPRESSION__RIGHT;

  /**
   * The feature id for the '<em><b>Logic Ex</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__LOGIC_EX = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>True Ex</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__TRUE_EX = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>False Ex</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__FALSE_EX = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.LogicOperatorImpl <em>Logic Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.LogicOperatorImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getLogicOperator()
   * @generated
   */
  int LOGIC_OPERATOR = 5;

  /**
   * The number of structural features of the '<em>Logic Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_OPERATOR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.EqualImpl <em>Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.EqualImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getEqual()
   * @generated
   */
  int EQUAL = 6;

  /**
   * The feature id for the '<em><b>Equal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__EQUAL = LOGIC_OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_FEATURE_COUNT = LOGIC_OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.MoreOrEqualImpl <em>More Or Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.MoreOrEqualImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getMoreOrEqual()
   * @generated
   */
  int MORE_OR_EQUAL = 7;

  /**
   * The feature id for the '<em><b>More Or Equal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MORE_OR_EQUAL__MORE_OR_EQUAL = LOGIC_OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>More Or Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MORE_OR_EQUAL_FEATURE_COUNT = LOGIC_OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.LessOrEqualImpl <em>Less Or Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.LessOrEqualImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getLessOrEqual()
   * @generated
   */
  int LESS_OR_EQUAL = 8;

  /**
   * The feature id for the '<em><b>Less Or Equal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_OR_EQUAL__LESS_OR_EQUAL = LOGIC_OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Less Or Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_OR_EQUAL_FEATURE_COUNT = LOGIC_OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.DifferentImpl <em>Different</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.DifferentImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getDifferent()
   * @generated
   */
  int DIFFERENT = 9;

  /**
   * The feature id for the '<em><b>Different</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFERENT__DIFFERENT = LOGIC_OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Different</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFERENT_FEATURE_COUNT = LOGIC_OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.MoreImpl <em>More</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.MoreImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getMore()
   * @generated
   */
  int MORE = 10;

  /**
   * The feature id for the '<em><b>More</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MORE__MORE = LOGIC_OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>More</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MORE_FEATURE_COUNT = LOGIC_OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.LessImpl <em>Less</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.LessImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getLess()
   * @generated
   */
  int LESS = 11;

  /**
   * The feature id for the '<em><b>Less</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS__LESS = LOGIC_OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Less</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_FEATURE_COUNT = LOGIC_OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.OperatorImpl <em>Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.OperatorImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 12;

  /**
   * The number of structural features of the '<em>Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.SubtractImpl <em>Subtract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.SubtractImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getSubtract()
   * @generated
   */
  int SUBTRACT = 13;

  /**
   * The feature id for the '<em><b>Minus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACT__MINUS = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Subtract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACT_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.AddImpl <em>Add</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.AddImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getAdd()
   * @generated
   */
  int ADD = 14;

  /**
   * The feature id for the '<em><b>Plus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__PLUS = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Add</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.MultiplyImpl <em>Multiply</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.MultiplyImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getMultiply()
   * @generated
   */
  int MULTIPLY = 15;

  /**
   * The feature id for the '<em><b>Times</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLY__TIMES = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Multiply</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLY_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fm.pucrs.br.sCH.impl.DivideImpl <em>Divide</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fm.pucrs.br.sCH.impl.DivideImpl
   * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getDivide()
   * @generated
   */
  int DIVIDE = 16;

  /**
   * The feature id for the '<em><b>Diveded</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__DIVEDED = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Divide</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fm.pucrs.br.sCH.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link fm.pucrs.br.sCH.Model#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see fm.pucrs.br.sCH.Model#getExpressions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Expressions();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see fm.pucrs.br.sCH.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute list '{@link fm.pucrs.br.sCH.Expression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see fm.pucrs.br.sCH.Expression#getValue()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Value();

  /**
   * Returns the meta object for the attribute list '{@link fm.pucrs.br.sCH.Expression#getIdentifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Identifier</em>'.
   * @see fm.pucrs.br.sCH.Expression#getIdentifier()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Identifier();

  /**
   * Returns the meta object for the attribute list '{@link fm.pucrs.br.sCH.Expression#getBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Bool</em>'.
   * @see fm.pucrs.br.sCH.Expression#getBool()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Bool();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Expression#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see fm.pucrs.br.sCH.Expression#getStr()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Str();

  /**
   * Returns the meta object for the containment reference '{@link fm.pucrs.br.sCH.Expression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Op</em>'.
   * @see fm.pucrs.br.sCH.Expression#getOp()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link fm.pucrs.br.sCH.Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fm.pucrs.br.sCH.Expression#getLeft()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Left();

  /**
   * Returns the meta object for the containment reference list '{@link fm.pucrs.br.sCH.Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see fm.pucrs.br.sCH.Expression#getRight()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Right();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Define <em>Define</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Define</em>'.
   * @see fm.pucrs.br.sCH.Define
   * @generated
   */
  EClass getDefine();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Define#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see fm.pucrs.br.sCH.Define#getId()
   * @see #getDefine()
   * @generated
   */
  EAttribute getDefine_Id();

  /**
   * Returns the meta object for the containment reference list '{@link fm.pucrs.br.sCH.Define#getEx <em>Ex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ex</em>'.
   * @see fm.pucrs.br.sCH.Define#getEx()
   * @see #getDefine()
   * @generated
   */
  EReference getDefine_Ex();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Lambda <em>Lambda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lambda</em>'.
   * @see fm.pucrs.br.sCH.Lambda
   * @generated
   */
  EClass getLambda();

  /**
   * Returns the meta object for the attribute list '{@link fm.pucrs.br.sCH.Lambda#getOuput <em>Ouput</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Ouput</em>'.
   * @see fm.pucrs.br.sCH.Lambda#getOuput()
   * @see #getLambda()
   * @generated
   */
  EAttribute getLambda_Ouput();

  /**
   * Returns the meta object for the containment reference '{@link fm.pucrs.br.sCH.Lambda#getEx <em>Ex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ex</em>'.
   * @see fm.pucrs.br.sCH.Lambda#getEx()
   * @see #getLambda()
   * @generated
   */
  EReference getLambda_Ex();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see fm.pucrs.br.sCH.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the containment reference '{@link fm.pucrs.br.sCH.If#getLogicEx <em>Logic Ex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Logic Ex</em>'.
   * @see fm.pucrs.br.sCH.If#getLogicEx()
   * @see #getIf()
   * @generated
   */
  EReference getIf_LogicEx();

  /**
   * Returns the meta object for the containment reference '{@link fm.pucrs.br.sCH.If#getTrueEx <em>True Ex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>True Ex</em>'.
   * @see fm.pucrs.br.sCH.If#getTrueEx()
   * @see #getIf()
   * @generated
   */
  EReference getIf_TrueEx();

  /**
   * Returns the meta object for the containment reference '{@link fm.pucrs.br.sCH.If#getFalseEx <em>False Ex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>False Ex</em>'.
   * @see fm.pucrs.br.sCH.If#getFalseEx()
   * @see #getIf()
   * @generated
   */
  EReference getIf_FalseEx();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.LogicOperator <em>Logic Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic Operator</em>'.
   * @see fm.pucrs.br.sCH.LogicOperator
   * @generated
   */
  EClass getLogicOperator();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Equal <em>Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equal</em>'.
   * @see fm.pucrs.br.sCH.Equal
   * @generated
   */
  EClass getEqual();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Equal#getEqual <em>Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Equal</em>'.
   * @see fm.pucrs.br.sCH.Equal#getEqual()
   * @see #getEqual()
   * @generated
   */
  EAttribute getEqual_Equal();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.MoreOrEqual <em>More Or Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>More Or Equal</em>'.
   * @see fm.pucrs.br.sCH.MoreOrEqual
   * @generated
   */
  EClass getMoreOrEqual();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.MoreOrEqual#getMoreOrEqual <em>More Or Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>More Or Equal</em>'.
   * @see fm.pucrs.br.sCH.MoreOrEqual#getMoreOrEqual()
   * @see #getMoreOrEqual()
   * @generated
   */
  EAttribute getMoreOrEqual_MoreOrEqual();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.LessOrEqual <em>Less Or Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Less Or Equal</em>'.
   * @see fm.pucrs.br.sCH.LessOrEqual
   * @generated
   */
  EClass getLessOrEqual();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.LessOrEqual#getLessOrEqual <em>Less Or Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Less Or Equal</em>'.
   * @see fm.pucrs.br.sCH.LessOrEqual#getLessOrEqual()
   * @see #getLessOrEqual()
   * @generated
   */
  EAttribute getLessOrEqual_LessOrEqual();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Different <em>Different</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Different</em>'.
   * @see fm.pucrs.br.sCH.Different
   * @generated
   */
  EClass getDifferent();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Different#getDifferent <em>Different</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Different</em>'.
   * @see fm.pucrs.br.sCH.Different#getDifferent()
   * @see #getDifferent()
   * @generated
   */
  EAttribute getDifferent_Different();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.More <em>More</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>More</em>'.
   * @see fm.pucrs.br.sCH.More
   * @generated
   */
  EClass getMore();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.More#getMore <em>More</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>More</em>'.
   * @see fm.pucrs.br.sCH.More#getMore()
   * @see #getMore()
   * @generated
   */
  EAttribute getMore_More();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Less <em>Less</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Less</em>'.
   * @see fm.pucrs.br.sCH.Less
   * @generated
   */
  EClass getLess();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Less#getLess <em>Less</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Less</em>'.
   * @see fm.pucrs.br.sCH.Less#getLess()
   * @see #getLess()
   * @generated
   */
  EAttribute getLess_Less();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operator</em>'.
   * @see fm.pucrs.br.sCH.Operator
   * @generated
   */
  EClass getOperator();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Subtract <em>Subtract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subtract</em>'.
   * @see fm.pucrs.br.sCH.Subtract
   * @generated
   */
  EClass getSubtract();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Subtract#getMinus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Minus</em>'.
   * @see fm.pucrs.br.sCH.Subtract#getMinus()
   * @see #getSubtract()
   * @generated
   */
  EAttribute getSubtract_Minus();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Add <em>Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add</em>'.
   * @see fm.pucrs.br.sCH.Add
   * @generated
   */
  EClass getAdd();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Add#getPlus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Plus</em>'.
   * @see fm.pucrs.br.sCH.Add#getPlus()
   * @see #getAdd()
   * @generated
   */
  EAttribute getAdd_Plus();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Multiply <em>Multiply</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiply</em>'.
   * @see fm.pucrs.br.sCH.Multiply
   * @generated
   */
  EClass getMultiply();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Multiply#getTimes <em>Times</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Times</em>'.
   * @see fm.pucrs.br.sCH.Multiply#getTimes()
   * @see #getMultiply()
   * @generated
   */
  EAttribute getMultiply_Times();

  /**
   * Returns the meta object for class '{@link fm.pucrs.br.sCH.Divide <em>Divide</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Divide</em>'.
   * @see fm.pucrs.br.sCH.Divide
   * @generated
   */
  EClass getDivide();

  /**
   * Returns the meta object for the attribute '{@link fm.pucrs.br.sCH.Divide#getDiveded <em>Diveded</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Diveded</em>'.
   * @see fm.pucrs.br.sCH.Divide#getDiveded()
   * @see #getDivide()
   * @generated
   */
  EAttribute getDivide_Diveded();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SCHFactory getSCHFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.ModelImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__EXPRESSIONS = eINSTANCE.getModel_Expressions();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.ExpressionImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__VALUE = eINSTANCE.getExpression_Value();

    /**
     * The meta object literal for the '<em><b>Identifier</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__IDENTIFIER = eINSTANCE.getExpression_Identifier();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__BOOL = eINSTANCE.getExpression_Bool();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__STR = eINSTANCE.getExpression_Str();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__OP = eINSTANCE.getExpression_Op();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__LEFT = eINSTANCE.getExpression_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__RIGHT = eINSTANCE.getExpression_Right();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.DefineImpl <em>Define</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.DefineImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getDefine()
     * @generated
     */
    EClass DEFINE = eINSTANCE.getDefine();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINE__ID = eINSTANCE.getDefine_Id();

    /**
     * The meta object literal for the '<em><b>Ex</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINE__EX = eINSTANCE.getDefine_Ex();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.LambdaImpl <em>Lambda</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.LambdaImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getLambda()
     * @generated
     */
    EClass LAMBDA = eINSTANCE.getLambda();

    /**
     * The meta object literal for the '<em><b>Ouput</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAMBDA__OUPUT = eINSTANCE.getLambda_Ouput();

    /**
     * The meta object literal for the '<em><b>Ex</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAMBDA__EX = eINSTANCE.getLambda_Ex();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.IfImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Logic Ex</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__LOGIC_EX = eINSTANCE.getIf_LogicEx();

    /**
     * The meta object literal for the '<em><b>True Ex</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__TRUE_EX = eINSTANCE.getIf_TrueEx();

    /**
     * The meta object literal for the '<em><b>False Ex</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__FALSE_EX = eINSTANCE.getIf_FalseEx();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.LogicOperatorImpl <em>Logic Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.LogicOperatorImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getLogicOperator()
     * @generated
     */
    EClass LOGIC_OPERATOR = eINSTANCE.getLogicOperator();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.EqualImpl <em>Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.EqualImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getEqual()
     * @generated
     */
    EClass EQUAL = eINSTANCE.getEqual();

    /**
     * The meta object literal for the '<em><b>Equal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUAL__EQUAL = eINSTANCE.getEqual_Equal();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.MoreOrEqualImpl <em>More Or Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.MoreOrEqualImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getMoreOrEqual()
     * @generated
     */
    EClass MORE_OR_EQUAL = eINSTANCE.getMoreOrEqual();

    /**
     * The meta object literal for the '<em><b>More Or Equal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MORE_OR_EQUAL__MORE_OR_EQUAL = eINSTANCE.getMoreOrEqual_MoreOrEqual();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.LessOrEqualImpl <em>Less Or Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.LessOrEqualImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getLessOrEqual()
     * @generated
     */
    EClass LESS_OR_EQUAL = eINSTANCE.getLessOrEqual();

    /**
     * The meta object literal for the '<em><b>Less Or Equal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LESS_OR_EQUAL__LESS_OR_EQUAL = eINSTANCE.getLessOrEqual_LessOrEqual();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.DifferentImpl <em>Different</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.DifferentImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getDifferent()
     * @generated
     */
    EClass DIFFERENT = eINSTANCE.getDifferent();

    /**
     * The meta object literal for the '<em><b>Different</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIFFERENT__DIFFERENT = eINSTANCE.getDifferent_Different();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.MoreImpl <em>More</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.MoreImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getMore()
     * @generated
     */
    EClass MORE = eINSTANCE.getMore();

    /**
     * The meta object literal for the '<em><b>More</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MORE__MORE = eINSTANCE.getMore_More();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.LessImpl <em>Less</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.LessImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getLess()
     * @generated
     */
    EClass LESS = eINSTANCE.getLess();

    /**
     * The meta object literal for the '<em><b>Less</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LESS__LESS = eINSTANCE.getLess_Less();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.OperatorImpl <em>Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.OperatorImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getOperator()
     * @generated
     */
    EClass OPERATOR = eINSTANCE.getOperator();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.SubtractImpl <em>Subtract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.SubtractImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getSubtract()
     * @generated
     */
    EClass SUBTRACT = eINSTANCE.getSubtract();

    /**
     * The meta object literal for the '<em><b>Minus</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBTRACT__MINUS = eINSTANCE.getSubtract_Minus();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.AddImpl <em>Add</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.AddImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getAdd()
     * @generated
     */
    EClass ADD = eINSTANCE.getAdd();

    /**
     * The meta object literal for the '<em><b>Plus</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD__PLUS = eINSTANCE.getAdd_Plus();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.MultiplyImpl <em>Multiply</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.MultiplyImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getMultiply()
     * @generated
     */
    EClass MULTIPLY = eINSTANCE.getMultiply();

    /**
     * The meta object literal for the '<em><b>Times</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLY__TIMES = eINSTANCE.getMultiply_Times();

    /**
     * The meta object literal for the '{@link fm.pucrs.br.sCH.impl.DivideImpl <em>Divide</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fm.pucrs.br.sCH.impl.DivideImpl
     * @see fm.pucrs.br.sCH.impl.SCHPackageImpl#getDivide()
     * @generated
     */
    EClass DIVIDE = eINSTANCE.getDivide();

    /**
     * The meta object literal for the '<em><b>Diveded</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIVIDE__DIVEDED = eINSTANCE.getDivide_Diveded();

  }

} //SCHPackage
