/**
 * generated by Xtext 2.13.0
 */
package fm.pucrs.br.sCH;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ST Rexp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link fm.pucrs.br.sCH.STRexp#getSvalue <em>Svalue</em>}</li>
 * </ul>
 * </p>
 *
 * @see fm.pucrs.br.sCH.SCHPackage#getSTRexp()
 * @model
 * @generated
 */
public interface STRexp extends Atom
{
  /**
   * Returns the value of the '<em><b>Svalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Svalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Svalue</em>' attribute.
   * @see #setSvalue(String)
   * @see fm.pucrs.br.sCH.SCHPackage#getSTRexp_Svalue()
   * @model
   * @generated
   */
  String getSvalue();

  /**
   * Sets the value of the '{@link fm.pucrs.br.sCH.STRexp#getSvalue <em>Svalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Svalue</em>' attribute.
   * @see #getSvalue()
   * @generated
   */
  void setSvalue(String value);

} // STRexp
