/*
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SCHAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fm/pucrs/br/parser/antlr/internal/InternalSCH.tokens");
	}
}
