/**
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.validation;

import fm.pucrs.br.validation.AbstractSCHValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SCHValidator extends AbstractSCHValidator {
}
