/*
 * generated by Xtext 2.12.0
 */
package fm.pucrs.br.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSCHValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fm.pucrs.br.sCH.SCHPackage.eINSTANCE);
		return result;
	}
	
}
